### ISSUE TITLE
npm run package

### ISSUE THREAD

**Issue by zhaodagang** [HouseOps/HouseOps#39]
After npm run package
There are some wrong.

PS E:\HouseOps> npm run package

> HouseOps@0.3.0-beta package E:\HouseOps
> npm run build && build --publish never

> HouseOps@0.3.0-beta build E:\HouseOps
> concurrently "npm run build-main" "npm run build-renderer"

[1]
[1] > HouseOps@0.3.0-beta build-renderer E:\HouseOps
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[0]
[0] > HouseOps@0.3.0-beta build-main E:\HouseOps
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[0] Hash: 7cbacf150a5adca3c68b
[0] Version: webpack 4.12.0
[0] Time: 99869ms
[0] Built at: 2018-06-22 12:42:20
[0]                  Asset      Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  1.93 MiB       0  [emitted]  main
[0] ./app/main.prod.js.map     8 MiB       0  [emitted]  main
[0] [./app/main.dev.js] 4.47 KiB {0} [built]
[0] [./app/package.json] 532 bytes {0} [built]
[0] [./app/utils/external-logging.js] 852 bytes {0} [built]
[0] [./app/utils/google-analytics.js] 871 bytes {0} [built]
[0] [./node_modules/_moment@2.22.2@moment/locale sync recursive ^\.\/.*$] ./node_modules/_moment@2.22.2@moment/locale sync ^\.\/.*$ 2.91 KiB {0} [optional] [built]
[0] [./node_modules/_webpack@4.12.0@webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0]     + 441 hidden modules
[0] npm run build-main exited with code 0
[1] Hash: cbf329aa47791383f5c2
[1] Version: webpack 4.12.0
[1] Time: 151599ms
[1] Built at: 2018-06-22 12:43:12
[1]                                 Asset      Size  Chunks             Chunk Names
[1] f56d7d3470cf9d60593812561aff63c4.woff  88.8 KiB          [emitted]
[1]  c22f3806638273bd9e764fea0a812c51.eot  86.4 KiB          [emitted]
[1] d13388bee1190a551bb5d9c9f953a779.woff  86.3 KiB          [emitted]
[1]  062208ea882dd2a7e2fa8552c6f32e3b.eot  88.9 KiB          [emitted]
[1]  6d716ba49663310796d6cf4d6d8b65b2.ttf  88.7 KiB          [emitted]
[1]  76957eb0b3f1dd52766872b7dd6c04d6.ttf  86.2 KiB          [emitted]
[1]  18bf1696cafa9470ea8e635b43e1e032.svg  20.9 KiB          [emitted]
[1]                      renderer.prod.js  3.42 MiB    main  [emitted]  main
[1]                             style.css   231 KiB    main  [emitted]  main
[1]                  renderer.prod.js.map  10.3 MiB    main  [emitted]  main
[1]                         style.css.map  86 bytes    main  [emitted]  main
[1] [./app/containers/App.js] 9.1 KiB {main} [built]
[1] [./app/containers/DatabaseGraph.js] 7.3 KiB {main} [built]
[1] [./app/containers/DoScience.js] 4.15 KiB {main} [built]
[1] [./app/containers/ProcessesList.js] 17.6 KiB {main} [built]
[1] [./app/containers/Root.js] 1.67 KiB {main} [built]
[1] [./app/containers/ServerSettings.js] 4.69 KiB {main} [built]
[1] [./app/index.js] 1.93 KiB {main} [built]
[1] [./app/reducers/index.js] 333 bytes {main} [built]
[1] [./app/routes.js] 2.29 KiB {main} [built]
[1] [./app/store/configureStore.js] 251 bytes {main} [built]
[1] [./app/store/configureStore.prod.js] 897 bytes {main} [built]
[1] [./app/utils/checkVersion.js] 1.14 KiB {main} [built]
[1] [./app/utils/localStorageVariables.js] 379 bytes {main} [built]
[1] [./node_modules/_css-loader@0.28.11@css-loader/index.js??ref--7-2!./node_modules/_sass-loader@7.0.3@sass-loader/lib/loader.js!./app/app.global.scss] ./node_modules/_css-loader@0.28.11@css-loader??ref--7-2!./node_modules/_sass-loader@7.0.3@sass-loader/lib/loader.js!./app/app.global.scss 200 KiB [built]
[1] [electron] external "electron" 42 bytes {main} [built]
[1]     + 1128 hidden modules
[1] Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@4.0.0-beta.0@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js??ref--6-1!node_modules/_react-table@6.8.6@react-table/react-table.css:
[1]        2 modules
[1] Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@4.0.0-beta.0@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js??ref--7-2!node_modules/_sass-loader@7.0.3@sass-loader/lib/loader.js!app/app.global.scss:
[1]      6 assets
[1]     [./node_modules/_css-loader@0.28.11@css-loader/index.js??ref--7-2!./node_modules/_sass-loader@7.0.3@sass-loader/lib/loader.js!./app/app.global.scss] ./node_modules/_css-loader@0.28.11@css-loader??ref--7-2!./node_modules/_sass-loader@7.0.3@sass-loader/lib/loader.js!./app/app.global.scss 200 KiB {0} [built]
[1]         + 11 hidden modules
[1] npm run build-renderer exited with code 0
  • electron-builder version=20.15.1
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release\electron-builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.3 appOutDir=release\win-unpacked
Downloading tmp-3736-1-SHASUMS256.txt-2.0.3
[============================================>] 100.0% of 5.33 kB (5.33 kB/s)
Error: Cannot spawn E:\HouseOps\node_modules\_app-builder-bin@1.9.7@app-builder-bin\win\x64\app-builder.exe: Error: spawn EPERM
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at doSpawn (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:174:12)
    at Promise (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:371:28)
    at new Promise (<anonymous>)
    at executeAppBuilder (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:359:10)
    at E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:579:29
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:97:49)
    at E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:201:15    at WinPackager.resolveIcon (E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:567:69)
    at E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:551:31
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at _errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at doSpawn (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:174:12)
    at Promise (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:371:28)
    at new Promise (<anonymous>)
    at executeAppBuilder (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:359:10)
    at E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:579:29
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:97:49)
    at E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:201:15    at WinPackager.resolveIcon (E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:567:69)
    at E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:551:31
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at doSpawn (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:177:11)
    at Promise (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:371:28)
    at new Promise (<anonymous>)
    at executeAppBuilder (E:\HouseOps\node_modules\_builder-util@5.11.2@builder-util\src\util.ts:359:10)
    at E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\src\platformPackager.ts:579:29
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:97:49)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at new PromiseSpawn (E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:43:17)
    at E:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\generators.js:197:21    at build (E:\HouseOps\node_modules\_electron-builder-lib@20.15.1@electron-builder-lib\out\index.js:220:17)
    at build (E:\HouseOps\node_modules\_electron-builder@20.15.1@electron-builder\src\builder.ts:234:10)
    at then (E:\HouseOps\node_modules\_electron-builder@20.15.1@electron-builder\src\cli\cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HouseOps@0.3.0-beta package: `npm run build && build --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HouseOps@0.3.0-beta package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zdg\AppData\Roaming\npm-cache\_logs\2018-06-22T05_00_59_469Z-debug.log
PS E:\HouseOps>

**Comment by zhaodagang** [comment]
Afte  npm run package-win

PS E:\HouseOps> npm run package-win

> HouseOps@0.3.0-beta package-win E:\HouseOps
> npm run build && build --win --x64


> HouseOps@0.3.0-beta build E:\HouseOps
> concurrently "npm run build-main" "npm run build-renderer"

[0]
[0] > HouseOps@0.3.0-beta build-main E:\HouseOps
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[1]
[1] > HouseOps@0.3.0-beta build-renderer E:\HouseOps
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]





[0] Hash: 7cbacf150a5adca3c68b
[0] Version: webpack 4.12.0
[0] Time: 175966ms
[0] Built at: 2018-06-22 21:28:16
[0]                  Asset      Size  Chunks             Chunk Names
[0]     ./app/main.prod.js  1.93 MiB       0  [emitted]  main
[0] ./app/main.prod.js.map     8 MiB       0  [emitted]  main
[0] [./app/main.dev.js] 4.47 KiB {0} [built]
[0] [./app/package.json] 532 bytes {0} [built]
[0] [./app/utils/external-logging.js] 852 bytes {0} [built]
[0] [./app/utils/google-analytics.js] 871 bytes {0} [built]
[0] [./node_modules/_moment@2.22.2@moment/locale sync recursive ^\.\/.*$] ./node_modules/_moment@2.22.2@moment/locale sync ^\.\/.*$ 2.91 KiB {0} [optional] [built]
[0] [./node_modules/_webpack@4.12.0@webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
[0] [child_process] external "child_process" 42 bytes {0} [built]
[0] [crypto] external "crypto" 42 bytes {0} [built]
[0] [electron] external "electron" 42 bytes {0} [built]
[0] [events] external "events" 42 bytes {0} [built]
[0] [fs] external "fs" 42 bytes {0} [built]
[0] [https] external "https" 42 bytes {0} [built]
[0] [module] external "module" 42 bytes {0} [optional] [built]
[0] [os] external "os" 42 bytes {0} [built]
[0] [path] external "path" 42 bytes {0} [built]
[0]     + 441 hidden modules
[0] npm run build-main exited with code 0

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:364:12)
    at ReadStream.process.stdin.on (E:\HouseOps\node_modules\_concurrently@3.6.0@concurrently\src\main.js:306:26)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at TTY.onread (net.js:607:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HouseOps@0.3.0-beta build: `concurrently "npm run build-main" "npm run build-renderer"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HouseOps@0.3.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zdg\AppData\Roaming\npm-cache\_logs\2018-06-22T13_28_54_624Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HouseOps@0.3.0-beta package-win: `npm run build && build --win --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HouseOps@0.3.0-beta package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zdg\AppData\Roaming\npm-cache\_logs\2018-06-22T13_28_55_075Z-debug.log

**Comment by zhaodagang** [comment]
@jonatasfreitasv , this question is very import for me, please help me ,thank you very much!

**Comment by zhaodagang** [comment]
@jonatasfreitasv
