### ISSUE TITLE
 JavaScript heap out of memory

### ISSUE THREAD

**Issue by zhaodagang** [HouseOps/HouseOps#7]
![13](https://user-images.githubusercontent.com/33817963/40609343-f143f114-62a0-11e8-834b-bda8afde3fb0.jpg)

**Comment by jonatasfreitasv** [comment]
I fix this in 1.0.0-beta, please test again!

**Comment by jonatasfreitasv** [comment]
Hi @zhaodagang, you test build with new version?

**Comment by nh1571** [comment]
Clicking on the win is wrong, but it's actually running

**Comment by zhaodagang** [comment]
Test package width new version .

PS G:\HouseOps> npm run package

> HouseOps@1.0.0-beta package G:\HouseOps
> npm run build && build --publish never


> HouseOps@1.0.0-beta build G:\HouseOps
> concurrently "npm run build-main" "npm run build-renderer"

[1]
[1] > HouseOps@1.0.0-beta build-renderer G:\HouseOps
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[0]
[0] > HouseOps@1.0.0-beta build-main G:\HouseOps
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[0] Hash: 2e85e626dff858326ad8
[0] Version: webpack 3.12.0
[0] Time: 26425ms
[0]                  Asset     Size  Chunks                    Chunk Names
[0]     ./app/main.prod.js   841 kB       0  [emitted]  [big]  main
[0] ./app/main.prod.js.map  2.64 MB       0  [emitted]         main
[0] [./app/main.dev.js] ./app/main.dev.js 3.88 kB {0} [built]
[0] [./app/package.json] ./app/package.json 461 bytes {0} [built]
[0] [./app/utils/google-analytics.js] ./app/utils/google-analytics.js 871 bytes {0} [built]
[0]     + 245 hidden modules
[0] npm run build-main exited with code 0
[1] Hash: 3420088fd5be398be2a5
[1] Version: webpack 3.12.0
[1] Time: 65696ms
[1]                                Asset      Size  Chunks                    Chunk Names
[1] 18bf1696cafa9470ea8e635b43e1e032.svg   21.4 kB          [emitted]
[1]                     renderer.prod.js   1.94 MB       0  [emitted]  [big]  main
[1]                            style.css    220 kB       0  [emitted]         main
[1]                 renderer.prod.js.map   6.34 MB       0  [emitted]         main
[1]                        style.css.map  86 bytes       0  [emitted]         main
[1] [./app/app.global.scss] ./app/app.global.scss 41 bytes {0} [built]
[1] [./app/containers/App.js] ./app/containers/App.js 5.36 kB {0} [built]
[1] [./app/containers/DoScience.js] ./app/containers/DoScience.js 4.27 kB {0} [built]
[1] [./app/containers/Root.js] ./app/containers/Root.js 1.71 kB {0} [built]
[1] [./app/index.js] ./app/index.js 1.97 kB {0} [built]
[1] [./app/package.json] ./app/package.json 461 bytes {0} [built]
[1] [./app/reducers/index.js] ./app/reducers/index.js 333 bytes {0} [built]
[1] [./app/resources/houseOps_animated.svg] ./app/resources/houseOps_animated.svg 82 bytes {0} [built]
[1] [./app/routes.js] ./app/routes.js 1.69 kB {0} [built]
[1] [./app/store/configureStore.js] ./app/store/configureStore.js 251 bytes {0} [built]
[1] [./app/store/configureStore.prod.js] ./app/store/configureStore.prod.js 897 bytes {0} [built]
[1] [./app/utils/localStorageVariables.js] ./app/utils/localStorageVariables.js 238 bytes {0} [built]
[1] [./app/utils/query.js] ./app/utils/query.js 1.59 kB {0} [built]
[1] [./app/utils/toaster.js] ./app/utils/toaster.js 273 bytes {0} [built]
[1] [./node_modules/_css-loader@0.28.11@css-loader/index.js??ref--3-2!./node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js!./app/app.global.scss] ./node_modules/_css-loader@0.28.11@css-loader??ref--3-2!./node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js!./app/app.global.scss 189 kB [built]
[1]     + 853 hidden modules
[1] Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.2@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js??ref--2-1!node_modules/_react-table@6.8.6@react-table/react-table.css:
[1]        2 modules
[1] Child extract-text-webpack-plugin node_modules/_extract-text-webpack-plugin@3.0.2@extract-text-webpack-plugin/dist node_modules/_css-loader@0.28.11@css-loader/index.js??ref--3-2!node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js!app/app.global.scss:
[1]     [./node_modules/_css-loader@0.28.11@css-loader/index.js??ref--3-2!./node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js!./app/app.global.scss] ./node_modules/_css-loader@0.28.11@css-loader??ref--3-2!./node_modules/_sass-loader@6.0.7@sass-loader/lib/loader.js!./app/app.global.scss 189 kB {0} [built]
[1]         + 3 hidden modules
[1] npm run build-renderer exited with code 0
  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.8.7 appOutDir=release\win-unpacked
Downloading tmp-4792-0-electron-v1.8.7-win32-x64.zip
Error: connect ETIMEDOUT 52.216.226.56:443
Error: connect ETIMEDOUT 52.216.226.56:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (G:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\debuggability.js:400:19)
    at Promise._then (G:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:232:17)
    at Promise.then (G:\HouseOps\node_modules\_bluebird@3.5.1@bluebird\js\release\promise.js:125:17)
    at Object.args [as handler] (G:\HouseOps\node_modules\_electron-builder@19.56.2@electron-builder\src\cli\cli.ts:48:33)
    at Object.runCommand (G:\HouseOps\node_modules\_yargs@11.0.0@yargs\lib\command.js:235:44)    at Object.parseArgs [as _parseArgs] (G:\HouseOps\node_modules\_yargs@11.0.0@yargs\yargs.js:1042:24)
    at Object.get [as argv] (G:\HouseOps\node_modules\_yargs@11.0.0@yargs\yargs.js:957:21)
    at Object.<anonymous> (G:\HouseOps\node_modules\_electron-builder@19.56.2@electron-builder\src\cli\cli.ts:42:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HouseOps@1.0.0-beta package: `npm run build && build --publish never`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HouseOps@1.0.0-beta package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zdg\AppData\Roaming\npm-cache\_logs\2018-05-30T03_11_12_425Z-debug.log

**Comment by jonatasfreitasv** [comment]
You have Download electron timeout. Is your connection =/. Try again...

```
Downloading tmp-4792-0-electron-v1.8.7-win32-x64.zip
Error: connect ETIMEDOUT 52.216.226.56:443
```

**Comment by jonatasfreitasv** [comment]
@nh1571 Start Click House server with Docker!!! for tests...

**Comment by zhaodagang** [comment]
@jonatasfreitasv , try it again ,it is success.
But i open HouseOps.exe, it is wrong, like this:
![77](https://user-images.githubusercontent.com/33817963/40710349-fec45d8e-642a-11e8-9554-a7f9f786ba2b.jpg)

**Comment by jonatasfreitasv** [comment]
Yes @zhaodagang, in Windows packing have this bug =/.

I'm try to fix it in next days.

Thx a lot for your report.

**Comment by jonatasfreitasv** [comment]
I'm close this issue, have another equal. #6
